#!/bin/bash
python /home/vaschetti/maxarSrc/src/main_seg_tile_glbl_detections.py \
        --event_ix 6 \
        --when pre \
        --bs_det 1 \
        --size_det 600 \
        --stride_det 600 \
        --device_det cuda:3 \
        --text_prompt "bush" \
        --box_threshold 0.12 \
        --text_threshold 0.30 \
        --max_area_GD_boxes_mt2 6000 \
        --min_ratio_GD_boxes_edges 0.5 \
        --perc_reduce_tree_boxes 0.2 \
        --bs_seg 2 \
        --device_seg cuda:3 \
        --size_seg 600 \
        --stride_seg 400 \
        --ext_mt_build_box 0 \
        --road_width_mt 5 \
        --ESAM_num_parall_queries 5 \
        --out_dir_root "/home/vaschetti/maxarSrc/output/tiff/test_26_3_glbl"